version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Deploying model to production endpoint..."
      - python pipeline/deploy_prod.py

artifacts:
  files:
    - '**/*'
