version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt || true
      - npm install --prefix frontend || true
  pre_build:
    commands:
      - echo "Detecting changed folders..."
      - bash scripts/detect_changes.sh
  build:
    commands:
      - if [ "$FRONTEND_CHANGED" = "true" ]; then bash scripts/build_frontend.sh; fi
      - if [ "$BACKEND_CHANGED" = "true" ]; then bash scripts/build_backend.sh; fi
      - if [ "$ML_CHANGED" = "true" ]; then bash scripts/build_ml_model.sh; fi
  post_build:
    commands:
      - if [ "$ML_CHANGED" = "true" ]; then bash scripts/test_ml_model.sh; fi
      - if [ "$ML_CHANGED" = "true" ]; then bash scripts/deploy_ml_model.sh; fi

artifacts:
  files:
    - '**/*'
